# Generated by Django 3.2 on 2024-09-19 18:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart'},
        ),
        migrations.AddField(
            model_name='productimages',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1200, 400], upload_to='products/banners/images/', verbose_name='Фотография «Баннер»'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='thumbnail_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[300, 300], upload_to='products/thumbnails/images/', verbose_name='Фотография «Миниатюра»'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='cart_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1200, 800], upload_to='products/carts/images/', verbose_name='Фотография «Карточка»'),
        ),
    ]
