# Generated by Django 3.2 on 2024-09-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240920_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'объект «Изображения продуктов»', 'verbose_name_plural': 'объекты «Изображений продуктов»'},
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productimages', verbose_name='Изображения'),
        ),
    ]
