# Generated by Django 3.2 on 2024-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240920_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='banner_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/banners/images/', verbose_name='Фотография «Баннер»'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='cart_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/carts/images/', verbose_name='Фотография «Карточка»'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/thumbnails/images/', verbose_name='Фотография «Миниатюра»'),
        ),
    ]
