# Generated by Django 3.2 on 2024-09-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240920_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImagesDesktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_detail', models.ImageField(blank=True, default=None, null=True, upload_to='products/detail/images/', verbose_name='Фотография «Карточка»')),
                ('image_list', models.ImageField(blank=True, default=None, null=True, upload_to='products/list/images/', verbose_name='Фотография «Баннер»')),
                ('image_thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='products/thumbnails/images/', verbose_name='Фотография «Миниатюра»')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'verbose_name': 'объект «Изображения продуктов»',
                'verbose_name_plural': 'объекты «Изображений продуктов»',
            },
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
