# Generated by Django 3.2 on 2024-09-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240920_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesdesktop',
            name='image_list',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/list/images/', verbose_name='Фотография «Каталог»'),
        ),
        migrations.AlterField(
            model_name='productimagesdesktop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images_desktop', to='products.product'),
        ),
    ]
