# Generated by Django 3.2 on 2024-09-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240920_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagesdesktop',
            options={'default_related_name': 'product_images_desktop', 'verbose_name': '«Изображения продуктов»', 'verbose_name_plural': '«Изображения продуктов»'},
        ),
        migrations.AlterField(
            model_name='productimagesdesktop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
