# Generated by Django 3.2 on 2024-09-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20240921_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesdesktop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images_desktop', to='products.product', verbose_name='Продукт'),
        ),
    ]
